version: '3.3'
services:
  counterstrike:
    image: ich777/steamcmd:latest
    container_name: gs-csgo
    env_file:
      - stack.env
    dns:
      - 127.0.0.1
      - 1.1.1.1      
      - 8.8.8.8
    volumes:
      - ${HOST_STEAMCMD_FOLDER}:/serverdata/steamcmd
      - ${HOST_GAME_SERVER_FILES}:/serverdata/serverfiles
    ports:
      - 27015:27015
      - 27015:27015/udp
    networks:
      macvlan01:
        ipv4_address: "${GAMESERVER_IP}"
networks:
  macvlan01:
    external: true